# Generated by Django 5.1.1 on 2024-09-16 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publication_date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 9, 16, 10, 42, 2, 579640, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Publication Date",
            ),
        ),
    ]
